# Generated by Django 3.0.7 on 2020-06-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_title', models.CharField(max_length=200)),
                ('News_context', models.CharField(max_length=2000)),
                ('News_pub_date', models.DateField(verbose_name='news published date')),
            ],
        ),
        migrations.CreateModel(
            name='News_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_comment_text', models.CharField(max_length=2000)),
                ('news_comment_pub_date', models.DateField(verbose_name='comment published date')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.News')),
            ],
        ),
        migrations.DeleteModel(
            name='news_context',
        ),
        migrations.DeleteModel(
            name='news_title',
        ),
    ]
